### ISSUE TITLE
Unable to connect to Bridgefy maven repository

### ISSUE THREAD

**Issue by hikaru-coder** [bridgefy/bridgefy-android-sdk-sample#27]
I try to compile the code in Android Studio but I am unable to get the Bridgefy maven repository following the guide.

android {
    ...
    repositories {
         ...
         maven {
             url "http://maven.bridgefy.com/artifactory/libs-release-local"
             artifactUrls=["http://jcenter.bintray.com/"]
              }
        ...
        }
    ...
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
}

Please help. Thank you.

**Comment by okanulkr** [comment]
use repositories closure at settings.gradle

**Comment by Angelo96x** [comment]
> > use repositories closure at settings.gradle
> 
> I was able to solve it using the **repositories {}** closure in the **settings.gradle** file. What I mean is:
> 
> In the **settings.gradle**, use this:
> 
> repositories { ... maven { url "http://maven.bridgefy.com/artifactory/libs-release-local" artifactUrls=["http://jcenter.bintray.com/"] } ... }

How? When I do this I get this error:

> A problem occurred evaluating settings '<NAME>'.
> Could not find method repositories() for arguments [settings_6fp0f7x2oa2oq0gpl8w60rit3$_run_closure1@558ec3aa] on settings '<NAME>' of type org.gradle.initialization.DefaultSettings.

What is the solution?

**Comment by hoseinfo** [comment]
this url is not found url
I mean this:"http://maven.bridgefy.com/artifactory/libs-release-local"
and problem is that they do not answer any question about it!!!!!!!!!!!!!

**Comment by Angelo96x** [comment]
@hoseinfo 
It is just what I have seen, I also see that the problem exists since February, as it is possible that in 9 months they have not found a solution... :'(

**Comment by hoseinfo** [comment]
they solve that issue bro...
but a new error happen!!!!
