### ISSUE TITLE
Bridgefy Flutter SDK

### ISSUE THREAD

**Issue by amanxnanda** [bridgefy/bridgefy-android-sdk-sample#29]
Flutter is an emerging cross-platform framework. I want bridgefy to support flutter as well and there will be thousands of more people like me.

Create a bridgefy sdk for flutter.

**Comment by julian-bridgefy** [comment]
Thanks for your suggestion, 
It is in our roadmap to create the flutter version, we are renewing our SDK, wait to hear from us, 
We are excited to create the Flutter version.

**Comment by rahulraikwar00** [comment]
I still waiting for to hear form you ! are team still working on Flutter plugin for bridgefy? @julian-bridgefy
